version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: game_db
      MYSQL_USER: gameuser
      MYSQL_PASSWORD: gamepassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USER=gameuser
      - DB_PASSWORD=gamepassword
      - DB_NAME=game_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Map to the Nginx default port 80
    depends_on:
      - backend

volumes:
  db_data:
